project_id = "bgshgmqtytwnyuqojqor"

[functions]
enabled = true
request_timeout_ms = 30000
verify_jwt = true

[functions.parse-financial-emails]
verify_jwt = true

[functions.fetch-gmail-emails]
verify_jwt = true

[functions.aggregate-financials]
verify_jwt = true